const data = {
  origins: [
    { name: "United States", code: "US" },
    { name: "Canada", code: "CA" },
    { name: "United Kingdom", code: "UK" },
    { name: "France", code: "FR" },
    { name: "Germany", code: "DE" },
  ],
  conditions: [
    { value: "Mint", label: "Mint" },
    { value: "Near Mint", label: "Near Mint" },
    { value: "Very Good", label: "Very Good" },
    { value: "Good", label: "Good" },
    { value: "Fair", label: "Fair" },
    { value: "Poor", label: "Poor" },
  ],
  rolledFolded: [
    { value: "Rolled", label: "Rolled" },
    { value: "Folded", label: "Folded" },
  ],
  formats: [
    { value: "US 1 Sheet", label: "US 1 Sheet" },
    { value: "US Halfsheet", label: "US Halfsheet" },
    { value: "US Lobby Se", label: "US Lobby Se" },
    { value: "US Insert", label: "US Insert" },
    { value: "US Window Card", lable: "US Window Card" },
    { value: "German A0", label: "German A0" },
    { value: "German A1", label: "German A1" },
    { value: "German A2", label: "German A2" },
    { value: "German Lobby Cards", label: "German Lobby Cards" },
    { value: "Japanese B1", label: "Japanese B1" },
    { value: "Japanese B2", label: "Japanese B2" },
    { value: "Japanese B3", label: "Japanese B3" },
    { value: "Japanese B4", label: "Japanese B4" },
    { value: "Japanese B5", label: "Japanese B5" },
    { value: "French Grande", label: "French Grande" },
    { value: "French Half Grande", label: "French Half Grande" },
    { value: "French Pantalon", label: "French Pantalon" },
    { value: "French Moyenne", label: "French Moyenne" },
    { value: "French Petite", label: "French Petite" },
    { value: "French Lobby Cards", label: "French Lobby Cards" },
    { value: "Italian Foglio", label: "Italian Foglio" },
    { value: "Italian 2 Foglio", label: "Italian 2 Foglio" },
    { value: "Italian 4 Foglio", label: "Italian 4 Foglio" },
    { value: "Italian Locandina", label: "Italian Locandina" },
    { value: " Italian Photobusta", label: " Italian Photobusta" },
    { value: "UK Quad", label: "UK Quad" },
    { value: "UK 1 Sheet", label: "UK 1 Sheet" },
    { value: "UK Double Crown", label: "UK Double Crown" },
    { value: "UK 3 Sheet", label: "UK 3 Sheet" },
    { value: "UK 6 Sheet", label: "UK 6 Sheet" },
    { value: "UK Front of House set", label: "UK Front of House set" },
  ],
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
